spring.datasource.url=jdbc:mysql://localhost:3306/newproject
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
weather.api.key=d848538f813f3d00eed487b3c2ee4591


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=haripriya0521@gmail.com
spring.mail.password =tpox ocro dhdc jud
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
